import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Navbar from "@/components/layout/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ramoena",
  description: "Created By O. Riastanjung - Design By BuildWithAngga - Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(montserrat.className,"bg-black-1 text-white")}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
